service: ${env:PRJ}-service
custom:
  secrets:
    dev: 
      db_creds: ${ssm:/aws/reference/secretsmanager/dev/rds-secret~true}
      db_host: ${ssm:/dev/db-host}
      db_name: ${ssm:/dev/db-name}
      db_port: 3306
      account_id: ${ssm:/dev/account-id}
      region: ${ssm:/dev/region}
    #local: ${file(local_secrets.json)}
provider:
  name: aws
  runtime: python3.7
  deploymentBucket:
    name: ${ssm:/dev/lambda-s3-bucket}
  role: ${ssm:/dev/lambda-role-arn}
  stage:  ${opt:stage,'dev'}
  region: us-east-1
  vpc:
    securityGroupIds:
      - ${ssm:/dev/lambda-sg}
    subnetIds:
      - ${ssm:/dev/private-subnet-1}
      - ${ssm:/dev/private-subnet-2}
  environment:
    #DB_NAME: ${self:custom.secrets.${self:provider.stage}.db_name}
    DB_USER: ${self:custom.secrets.${self:provider.stage}.db_creds.username}
    DB_PASSWORD: ${self:custom.secrets.${self:provider.stage}.db_creds.password}
    #DB_HOST: ${self:custom.secrets.${self:provider.stage}.db_host}
    DB_PORT: ${self:custom.secrets.${self:provider.stage}.db_port}
    #ACCOUNT_ID: ${self:custom.secrets.${self:provider.stage}.account_id}
    #REGION: ${self:custom.secrets.${self:provider.stage}.region}
    SERVICE_NAME: ${self:service}
    STAGE: ${self:provider.stage}

functions:
  currentTime:
    handler: handler.endpoint
    events:
      - http:
          path: ping
          method: get
